### ISSUE TITLE
Bug: Where im trying to setup a instance

### ISSUE THREAD

**Issue by xbdmHQ** [realaravinth/libmedium#22]
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) }', src/data.rs:156:22
stack backtrace:
   0:     0x562f2586073a - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x562f2586073a - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x562f2586073a - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x562f2586073a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x562f258847ce - core::fmt::write::h032658c119c720d7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x562f2585a8c5 - std::io::Write::write_fmt::h299fc90dfae41c0d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x562f25860505 - std::sys_common::backtrace::_print::heb70d25df9937e3f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x562f25860505 - std::sys_common::backtrace::print::had745c0a76b8b521
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x562f25861cef - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x562f25861a2b - std::panicking::default_hook::h1cc3af63455a163c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x562f258623fc - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0x562f25862199 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
  12:     0x562f25860bec - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x562f25861ea2 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0x562f25212ae3 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0x562f25212f73 - core::result::unwrap_failed::h62abf61e411aaa08
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
  16:     0x562f2525f30a - actix_web::handler::handler_service::{{closure}}::{{closure}}::h1795eeccfd12fc3d
  17:     0x562f2525c6c8 - <actix_web::resource::Resource<T> as actix_web::service::HttpServiceFactory>::register::{{closure}}::{{closure}}::h613d1c2e28e32d57
  18:     0x562f2524026a - <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll::hacc455b242a3b6b9
  19:     0x562f2533d2a4 - <actix_web::middleware::compress::CompressResponse<S,B> as core::future::future::Future>::poll::ha027aa0a2f5ed4ae
  20:     0x562f2530b0bb - <actix_service::map_err::MapErrFuture<A,Req,F,E> as core::future::future::Future>::poll::he8278bcf1c686a6d
  21:     0x562f2527f9f5 - actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response::h863068fba6eddaa3
  22:     0x562f25320e93 - <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll::hd4b327cb086aefc9
  23:     0x562f2532330a - <actix_service::and_then::AndThenServiceResponse<A,B,Req> as core::future::future::Future>::poll::hea50214fb5625f2d
  24:     0x562f25348c9c - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h668043c807f6d332
  25:     0x562f2528dd1c - tokio::runtime::task::core::Core<T,S>::poll::h196be2531146876c
  26:     0x562f252e976c - tokio::runtime::task::harness::Harness<T,S>::poll::hae2e84d34d55e88a
  27:     0x562f25827358 - tokio::task::local::LocalSet::tick::h07dd8201fb19aa81
  28:     0x562f255efd8c - std::thread::local::LocalKey<T>::with::h3c5feeed2d8abd42
  29:     0x562f255d72d9 - <core::pin::Pin<P> as core::future::future::Future>::poll::h80498f0988e18f7c
  30:     0x562f255fff7e - tokio::runtime::scheduler::current_thread::Context::enter::hc872c3c19e966739
  31:     0x562f255daaff - tokio::macros::scoped_tls::ScopedKey<T>::set::h3d492eb8f9b5897b
  32:     0x562f255ffabf - tokio::runtime::scheduler::current_thread::CurrentThread::block_on::hdbb061d7262b6c61
  33:     0x562f255e3bb2 - tokio::runtime::runtime::Runtime::block_on::hf3aa5997238783ae
  34:     0x562f255e49ba - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a6167aa3ee126f0
  35:     0x562f255dfdbc - core::ops::function::FnOnce::call_once{{vtable.shim}}::h025d4788b77bad97
  36:     0x562f25865d73 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb77d8d72ebcf79c4                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
  37:     0x562f25865d73 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc08c3353e1568487                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
  38:     0x562f25865d73 - std::sys::unix::thread::Thread::new::thread_start::h7168e596cd5e5ce6
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys/unix/thread.rs:108:17
  39:     0x7f776d921ea7 - start_thread
  40:     0x7f776d6f5a2f - clone
  41:                0x0 - <unknown>
```

**Comment by xbdmHQ** [comment]
@realaravinth

**Comment by realaravinth** [comment]
My apologies, I seemed to have missed this issue somehow! Please tell me which version of libmedium you were trying to run. Build details can be found at `/api/v1/meta/build` (example: https://libmedium.batsense.net/api/v1/meta/build).

If it is the latest version, then [this line](https://github.com/realaravinth/libmedium/blob/ebf39bd7c3d10f10f036abd01c7bbc8362f506a7/src/data.rs#L156) is panicking and crashing. That line shuld break only when the GraphQL API is misbehaving or the client GraphQL code is broken. I'm still able to read articiles on my instance, so this has to be an article-specific thing where an unexpected parameter is used in the GraphQL schema.

If the instance crashed when you tried to read an article, please share its link :)

**Comment by xbdmHQ** [comment]
> My apologies, I seemed to have missed this issue somehow! Please tell me which version of libmedium you were trying to run. Build details can be found at `/api/v1/meta/build` (example: https://libmedium.batsense.net/api/v1/meta/build).
> 
> If it is the latest version, then [this line](https://github.com/realaravinth/libmedium/blob/ebf39bd7c3d10f10f036abd01c7bbc8362f506a7/src/data.rs#L156) is panicking and crashing. That line shuld break only when the GraphQL API is misbehaving or the client GraphQL code is broken. I'm still able to read articiles on my instance, so this has to be an article-specific thing where an unexpected parameter is used in the GraphQL schema.
> 
> If the instance crashed when you tried to read an article, please share its link :)

I tested on the demo artictle

**Comment by realaravinth** [comment]
I'm sorry, I'm unable to reproduce it on my end. I tried with tow different machines and IPs (one of them has a dirty IP, always trips CAPTCHAs) hoping to get blocked/denied service, but both of them went through. If this issue persists, please show me the output of the following command run from the machine where you are trying to deploy libmedium:

```bash
curl --location 'https://medium.com/_/graphql' \
--header 'Content-Type: application/json' \
--header 'Cookie: __cfruid=c42450750ac3d0536b1067f537242d2d46a6378e-1690668778; sid=1:+AL0c7GTXtMjhveT4p4LhZkDkd4UI2tfw23O+DulMo5IZk5wqeY879ism0QxqeQv; uid=lo_1d312983506b' \
--data '{"query":"      query {\n        post(id:\"7158b1cdd50c\") {\n          title\n          createdAt\n          readingTime\n          creator {\n            id\n            name\n            imageId\n          }\n          content {\n            bodyModel {\n              paragraphs {\n                text\n                type\n                href\n                layout\n                markups {\n                  title\n                  type\n                  href\n                  userId\n                  start\n                  end\n                  anchorType\n                }\n                iframe {\n                  mediaResource {\n                    id\n                    href\n                    iframeSrc\n                    iframeWidth\n                    iframeHeight\n                  }\n                }\n                metadata {\n                  id\n                  originalWidth\n                  originalHeight\n                }\n              }\n            }\n          }\n        }\n      }\n","variables":{}}'
```

It's the GraphQL request made to Medium API. 

I'm off for the day, see you tomorrow :)
