### ISSUE TITLE
https://libmedium.batsense.net/@wjertzochjennifer/ returns 502

### ISSUE THREAD

**Issue by halkeye** [realaravinth/libmedium#33]
My local copy says
```
libmedium-7ff7db5b79-586gv libmedium thread 'actix-rt|system:0|arbiter:0' panicked at src/data.rs:183:73:
libmedium-7ff7db5b79-586gv libmedium called `Option::unwrap()` on a `None` value
libmedium-7ff7db5b79-586gv libmedium thread 'actix-rt|system:0|arbiter:0' panicked at src/data.rs:183:73:
libmedium-7ff7db5b79-586gv libmedium called `Option::unwrap()` on a `None` value
libmedium-7ff7db5b79-586gv libmedium thread 'actix-rt|system:0|arbiter:0' panicked at src/data.rs:183:73:
libmedium-7ff7db5b79-586gv libmedium called `Option::unwrap()` on a `None` value
libmedium-7ff7db5b79-586gv libmedium thread 'actix-rt|system:0|arbiter:0' panicked at src/data.rs:183:73:
libmedium-7ff7db5b79-586gv libmedium called `Option::unwrap()` on a `None` value
libmedium-7ff7db5b79-586gv libmedium thread 'actix-rt|system:0|arbiter:0' panicked at src/data.rs:183:73:
libmedium-7ff7db5b79-586gv libmedium called `Option::unwrap()` on a `None` value
libmedium-7ff7db5b79-586gv libmedium thread 'actix-rt|system:0|arbiter:0' panicked at src/data.rs:183:73:
libmedium-7ff7db5b79-586gv libmedium called `Option::unwrap()` on a `None` value
```

**Comment by KaKi87** [comment]
Hello,

Same HTTP code for the following URL on the same instance but also others : https://libmedium.batsense.net/exist-stories/what-s-the-happiest-day-of-the-week-75fa34902226

I'm just a user so I don't know if the server-side error is the same though.

**Comment by halkeye** [comment]
you'll want to report it (as a new issue) @ https://git.batsense.net/realaravinth/libmedium
as witnessed, this issue was fixed a while ago but code owner didn't really see it here.

**Comment by KaKi87** [comment]
Oh, actually [I did already make a report there 6 months ago](https://git.batsense.net/realaravinth/libmedium/issues/47).

**Comment by halkeye** [comment]
maybe its the one I fixed @ https://git.batsense.net/realaravinth/libmedium/commit/3111f3e25c7e4881e9f6e67b182112645fd7d6b7

It took me a while to notice it was

**Comment by halkeye** [comment]
tested it on my updated copy

```
libmedium-6b5f99989f-s4klp libmedium thread 'actix-rt|system:0|arbiter:2' panicked at src/data.rs:157:22:
libmedium-6b5f99989f-s4klp libmedium called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a string", line: 1, column: 542) }
libmedium-6b5f99989f-s4klp libmedium note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
libmedium-6b5f99989f-s4klp libmedium thread 'actix-rt|system:0|arbiter:3' panicked at src/data.rs:157:22:
libmedium-6b5f99989f-s4klp libmedium called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a string", line: 1, column: 542) }
libmedium-6b5f99989f-s4klp libmedium thread 'actix-rt|system:0|arbiter:0' panicked at src/data.rs:157:22:
libmedium-6b5f99989f-s4klp libmedium called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Decode, source: Error("invalid type: null, expected a string", line: 1, column: 542) }
```

You can probably update the ticket. I don't use it enough to try and figure out how to rust again.
